<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVVS71xi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVVS71xi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVVS71xi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVVS71xi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVVS71xi\App_KernelDevDebugContainer([
    'container.build_hash' => 'VVS71xi',
    'container.build_id' => '6149c2f2',
    'container.build_time' => 1774104900,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVVS71xi');
