services:
  php:
    build: # Fabrique une image à partir d'un Dockerfile
      context: ./php # context = endroit où se trouve Dockerfile pour PHP
    container_name: snowtricksphp
    ports:
      - 8187:80 # 8080 port externe, 80 port dans l'image (EXPOSE 80)
    volumes:
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./app:/var/www

  node:
    image: node:20
    container_name: snowtricksnode
    volumes:
      - ./:/var/www/public
    working_dir: /var/www/public
    command: sh -c "npm install && npm run dev"

  database:
    image: mysql:8.0
    container_name: snowtricksdb
    environment:
      MYSQL_ROOT_PASSWORD: snowtricks_pass # paramètre obligatoire, mot de passe d'administration de mysql
      MYSQL_DATABASE: snowtricks_db # Nom de la base de données
      MYSQL_USER: snowtricks_user # On met ce qu'on veut
      MYSQL_PASSWORD: snowtricks_pass # On met ce qu'on veut
    ports:
      - "4416:3306" # EXPOSE 3306
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: snowtricksdb # Nom du service de base de données
      PMA_USER: root
      PMA_PASSWORD: snowtricks_pass # MYSQL_ROOT_PASSWORD
    ports:
      - 8186:80 # EXPOSE 80
    depends_on:
      - database # Démarre APRES database

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: "none"
    ports:
      - "1125:1025" # Port SMTP
      - "8125:8025" # Interface web
