# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.jwtsecret: "%env(JWT_SECRET)%"

    # Dossiers finaux
    avatars_directory: "%kernel.project_dir%/public/uploads/avatars"
    featured_image_directory: "%kernel.project_dir%/public/uploads/featured_images"
    images_directory: "%kernel.project_dir%/public/uploads/images"

    # Dossiers temporaires
    avatars_tmp_directory: "%kernel.project_dir%/public/uploads/avatars_tmp"
    featured_image_tmp_directory: "%kernel.project_dir%/public/uploads/featured_images_tmp"
    images_tmp_directory: "%kernel.project_dir%/public/uploads/images_tmp"

services:
    # Default settings for services
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"

    # ==========================
    # Services pour les images temporaires
    # ==========================
    App\Service\AvatarTempService:
        arguments:
            $tempDir: "%avatars_tmp_directory%"
            $finalDir: "%avatars_directory%"

    App\Service\FeaturedImageTempService:
        arguments:
            $tempDir: "%featured_image_tmp_directory%"
            $finalDir: "%featured_image_directory%"

    App\Service\ImagesTempService:
        arguments:
            $tempDir: "%images_tmp_directory%"
            $finalDir: "%images_directory%"

    # ==========================
    # Services pour les images finales
    # ==========================
    App\Service\AvatarUploaderService:
        arguments:
            $targetDirectoryAvatar: "%avatars_directory%"

    App\Service\FeaturedImageUploaderService:
        arguments:
            $targetDirectoryFeaturedImage: "%featured_image_directory%"

    App\Service\ImagesUploaderService:
        arguments:
            $targetDirectoryImages: "%images_directory%"
